[project]
name = "swarm"
version = "0.0.1"
authors = ["Prajjwal Bhandari"]

[dependencies.xlib]
git = "https://github.com/Kintaro/rust-xlib.git"
branch = "class_hint"

[dependencies.xinerama]
git = "https://github.com/Kintaro/rust-xinerama.git"

[[bin]]
name = "swarm"
